### ISSUE TITLE
Chat/civil business 

### ISSUE THREAD

**Issue by Tompa84** [timmy21300/wildfire#2]
Hello, with a special bot/command you should be enabled to close the chat or other channels when needed instead for use of text , in that way no one should enabled to text unless you are staff/smt

You can choose what permissions civil business should have, I would recommend to have only for ppl with civil tag unless you sre staff/smt of course, in that way ppl only see what they should see depending of department/division

**Comment by timmy21300** [comment]
A lockdown command has been created. 

Only Admins can use this. 

/lockdown <status> [channel]

- Status choice of either Open or Close
- Channel is optional.
